---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: development
          - name: staging
          - name: production
  template:
    metadata:
      name: '{{name}}-namespace'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/xfoucron/monorepo-gitops.git'
        targetRevision: master
        path: 'deploy/namespace/overlays/{{name}}'
        kustomize: {}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
