---

image:
  repository: ghcr.io/xfoucron/monorepo-backend
  tag: v1.1.0

env:
  - name: RAILS_MASTER_KEY
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: RAILS_MASTER_KEY
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: backend-pg-cluster-app
        key: fqdn-uri

resources:
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 128m
    memory: 128Mi

ingress:
  enabled: true
  className: "nginx"
