---

resources:
  requests:
    cpu: 256m
    memory: 256Mi
  limits:
    cpu: 256m
    memory: 256Mi

ingress:
  hosts:
    - host: dev.notes-api.local
      paths:
        - path: /
          pathType: Prefix
