---

envSpecific:
  - name: APP_DOMAIN
    value: "http://staging.notes.local"

resources:
  requests:
    cpu: 512m
    memory: 512Mi
  limits:
    cpu: 512m
    memory: 512Mi

ingress:
  hosts:
    - host: staging.notes-api.local
      paths:
        - path: /
          pathType: Prefix
