---

image:
  repository: ghcr.io/xfoucron/monorepo-frontend
  tag: v1.1.0

resources:
  requests:
    cpu: 256m
    memory: 256Mi
  limits:
    cpu: 256m
    memory: 256Mi

service:
  port: 3000

ingress:
  enabled: true
  className: "nginx"
