---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-externalsecret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: app-secretstore
    kind: SecretStore
  target:
    name: app-secrets
