---

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: app-secretstore
spec:
  provider:
    vault:
      server: "http://vault.vault-system.svc.cluster.local:8200"
      version: "v2"
      auth:
        tokenSecretRef:
          key: "token"
          name: "vault-token"
