---

name: Helm
on: push  # yamllint disable-line rule:truthy
env:
  WORKING_DIR: deploy/charts/helm-chart
defaults:
  run:
    working-directory: deploy/charts/helm-chart
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Run Helm lint
        run: helm lint .

  release:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Package chart
        run: helm package .

      - name: Push chart to OCI
        run: |
          VERSION=$(grep '^version:' helm-chart/Chart.yaml | awk '{print $2'}
          helm push helm-chart-$VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
